name: Deploy Admin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Admin
        run: npm run build

      - name: Deploy Build
        run: |
          sudo rm -rf /var/www/admin/*
          sudo cp -r dist/* /var/www/admin/

      - name: Reload Nginx
        run: sudo systemctl reload nginx
